source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios,'10.0'

target 'BlogClient' do
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'KakaJSON'
  pod 'KingfisherWebP'
  pod 'R.swift'
  pod 'Masonry'
  pod 'MBProgressHUD'
end
