source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios,'10.0'

target 'BlogClient' do
  pod 'Alamofire', '5.6.4'
#  pod 'SwiftyJSON', '5.0.1'
  pod 'Kingfisher', '6.3.1'
  pod 'MJRefresh', '3.7.5'
#  pod 'KakaJSON'
  pod 'KingfisherWebP', '1.3.0'
  pod 'R.swift', '6.1.0'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'SnapKit', '~> 5.6.0'
end
